/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApplicationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-06T01:07:24.772878+02:00[Europe/Vienna]")
public class ApplicationResponse {
  /**
   * Gets or Sets applicationStatus
   */
  @JsonAdapter(ApplicationStatusEnum.Adapter.class)
  public enum ApplicationStatusEnum {
    RUNNING("RUNNING"),
    
    DATABASE_NOT_CONNECTED("DATABASE_NOT_CONNECTED");

    private String value;

    ApplicationStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ApplicationStatusEnum fromValue(String value) {
      for (ApplicationStatusEnum b : ApplicationStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ApplicationStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ApplicationStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ApplicationStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ApplicationStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_APPLICATION_STATUS = "applicationStatus";
  @SerializedName(SERIALIZED_NAME_APPLICATION_STATUS)
  private ApplicationStatusEnum applicationStatus;

  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;


  public ApplicationResponse applicationStatus(ApplicationStatusEnum applicationStatus) {
    
    this.applicationStatus = applicationStatus;
    return this;
  }

   /**
   * Get applicationStatus
   * @return applicationStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ApplicationStatusEnum getApplicationStatus() {
    return applicationStatus;
  }


  public void setApplicationStatus(ApplicationStatusEnum applicationStatus) {
    this.applicationStatus = applicationStatus;
  }


  public ApplicationResponse apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * Get apiVersion
   * @return apiVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationResponse applicationResponse = (ApplicationResponse) o;
    return Objects.equals(this.applicationStatus, applicationResponse.applicationStatus) &&
        Objects.equals(this.apiVersion, applicationResponse.apiVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationStatus, apiVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationResponse {\n");
    sb.append("    applicationStatus: ").append(toIndentedString(applicationStatus)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

